In [1]:
import numpy as np

In [9]:
matrix = np.array([
    [2, 2, 0, 0, 1, 0, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 2, 0],
    [0, 2, 0, 0, 1, 0, 1, 0, 0],
    [0, 0, 0, 0, 2, 2, 2, 2, 0],
    [0, 0, 0, 2, 0, 0, 0, 0, 2],
    [0, 2, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 0, 2, 0, 0],
    [0, 0, 0, 1, 2, 0, 2, 2, 0],
    [0, 1, 0, 0, 2, 2, 2, 2, 0],
    [0, 1, 0, 2, 2, 0, 2, 0, 0]
])
matrix

array([[2, 2, 0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 2, 0],
       [0, 2, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 2, 2, 2, 0],
       [0, 0, 0, 2, 0, 0, 0, 0, 2],
       [0, 2, 2, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 2, 0, 0],
       [0, 0, 0, 1, 2, 0, 2, 2, 0],
       [0, 1, 0, 0, 2, 2, 2, 2, 0],
       [0, 1, 0, 2, 2, 0, 2, 0, 0]])

In [31]:
nums_row = matrix.shape[0]
diff_columns = []

for i in range(nums_row):
    for j in range(i+1, nums_row):
        diff_columns.append(set(np.where(matrix[i] != matrix[j])[0]))

diff_columns

[{0, 1, 3, 4, 6, 7},
 {0},
 {0, 1, 4, 5, 6, 7},
 {0, 1, 3, 4, 6, 8},
 {0, 2, 6},
 {0, 1, 4, 6},
 {0, 1, 3, 4, 6, 7},
 {0, 1, 4, 5, 6, 7},
 {0, 1, 3, 4, 6},
 {1, 3, 4, 6, 7},
 {1, 3, 4, 5, 6},
 {1, 3, 7, 8},
 {1, 2, 3, 4, 7},
 {1, 3, 4, 6, 7},
 {1, 4, 6},
 {3, 4, 5, 6},
 {3, 4, 6, 7},
 {1, 4, 5, 6, 7},
 {1, 3, 4, 6, 8},
 {2, 6},
 {1, 4, 6},
 {1, 3, 4, 6, 7},
 {1, 4, 5, 6, 7},
 {1, 3, 4, 6},
 {3, 4, 5, 6, 7, 8},
 {1, 2, 4, 5, 6, 7},
 {5, 7},
 {3, 5},
 {1},
 {1, 3, 5, 7},
 {1, 2, 3, 4, 8},
 {3, 4, 6, 8},
 {3, 4, 6, 7, 8},
 {1, 3, 4, 5, 6, 7, 8},
 {1, 4, 6, 8},
 {1, 2, 4, 6},
 {1, 2, 3, 4, 6, 7},
 {1, 2, 4, 5, 6, 7},
 {1, 2, 3, 4, 6},
 {3, 7},
 {1, 5, 7},
 {1, 3},
 {1, 3, 5},
 {1, 3, 7},
 {3, 5, 7}]

In [76]:
nums_row = matrix.shape[0]
diff_columns = []
filter_col = [0, 1, 3, 6, 7] # 2 5 6 7

for i in range(nums_row):
    for j in range(i+1, nums_row):
        diff_columns.append(set(np.where(matrix[i, filter_col] != matrix[j, filter_col])[0]))

counts = 0
for i in diff_columns:
    if not i:
        counts += 1
print(counts)

0


In [23]:
for i in range(len(diff_columns)):
    if len(diff_columns[i]) == 1:
        print(i, diff_columns[i])

1 {0}
28 {1}


In [154]:
intensity = np.array([
    [0.90, 0.818, np.nan, np.nan, 0.189, np.nan, 0.30,  np.nan, np.nan],
    [np.nan, 0.219, np.nan, 0.267, np.nan, np.nan, np.nan, 0.816, np.nan],
    [np.nan, 0.713, np.nan, np.nan, 0.289, np.nan, 0.35,  np.nan, np.nan],
    [np.nan, np.nan, np.nan, np.nan, 0.515, 0.80,  0.90,  0.681, np.nan],
    [np.nan, np.nan, np.nan, 0.718, np.nan, np.nan, np.nan, np.nan, 0.75 ],
    [np.nan, 0.674, 0.87,  np.nan, 0.231, np.nan, np.nan, np.nan, np.nan],
    [np.nan, np.nan, np.nan, np.nan, 0.863, np.nan, 0.90, np.nan, np.nan],
    [np.nan, np.nan, np.nan, 0.416, 0.879, np.nan, 0.90,  0.759, np.nan],
    [np.nan, 0.149, np.nan, np.nan, 0.681, 0.80,  0.75,  0.721, np.nan],
    [np.nan, 0.20,  np.nan, 0.60,  0.70,  np.nan, 0.90,  np.nan, np.nan]
])
intensity = np.nan_to_num(intensity[:, [0, 1, 3, 6, 7]], nan=0.0)
intensity

array([[0.9  , 0.818, 0.   , 0.3  , 0.   ],
       [0.   , 0.219, 0.267, 0.   , 0.816],
       [0.   , 0.713, 0.   , 0.35 , 0.   ],
       [0.   , 0.   , 0.   , 0.9  , 0.681],
       [0.   , 0.   , 0.718, 0.   , 0.   ],
       [0.   , 0.674, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.9  , 0.   ],
       [0.   , 0.   , 0.416, 0.9  , 0.759],
       [0.   , 0.149, 0.   , 0.75 , 0.721],
       [0.   , 0.2  , 0.6  , 0.9  , 0.   ]])

In [155]:
prior_prob = np.array([0.2271, 0.0527, 0.0629, 0.0612, 0.0506, 0.1317, 0.0798, 0.1421, 0.1202, 0.0717])
prior_prob

array([0.2271, 0.0527, 0.0629, 0.0612, 0.0506, 0.1317, 0.0798, 0.1421,
       0.1202, 0.0717])

In [156]:
intensity_mplus = intensity[:, 1].reshape(-1, 1)
intensity_mplus

array([[0.818],
       [0.219],
       [0.713],
       [0.   ],
       [0.   ],
       [0.674],
       [0.   ],
       [0.   ],
       [0.149],
       [0.2  ]])

In [157]:
intensity_mminus = 1 - intensity[:, [i for i in range(intensity.shape[1]) if i != 1]]
intensity_mminus

array([[0.1  , 1.   , 0.7  , 1.   ],
       [1.   , 0.733, 1.   , 0.184],
       [1.   , 1.   , 0.65 , 1.   ],
       [1.   , 1.   , 0.1  , 0.319],
       [1.   , 0.282, 1.   , 1.   ],
       [1.   , 1.   , 1.   , 1.   ],
       [1.   , 1.   , 0.1  , 1.   ],
       [1.   , 0.584, 0.1  , 0.241],
       [1.   , 1.   , 0.25 , 0.279],
       [1.   , 0.4  , 0.1  , 1.   ]])

In [167]:
results = np.cumprod(intensity_mplus, axis=1)[:, -1] * np.nancumprod(intensity_mminus, axis=1)[:, -1] * prior_prob
# results /= np.nansum(results)
results.round(4)

array([0.013 , 0.0016, 0.0292, 0.    , 0.    , 0.0888, 0.    , 0.    ,
       0.0012, 0.0006])

In [1]:
5 // 2

2