In [1]:
from src.Model import *
from src.Simplify import *
from src.utils import *

In [2]:
dec_table = DecisionTable()
dec_table.import_from_json('./Data/data.json')

In [3]:
table3 = dec_table.export_table3()
df_table3 = show_table(table3)
df_table3

m1     m2    m3     m4     m5   m6    m7     m8    m9
Fault_ID                                                        
d1        0.9  0.818  0.00  0.000  0.189  0.0  0.30  0.000  0.00
d2        0.0  0.219  0.00  0.267  0.000  0.0  0.00  0.816  0.00
d3        0.0  0.713  0.00  0.000  0.289  0.0  0.35  0.000  0.00
d4        0.0  0.000  0.00  0.000  0.515  0.8  0.90  0.681  0.00
d5        0.0  0.000  0.00  0.718  0.000  0.0  0.00  0.000  0.75
d6        0.0  0.674  0.87  0.000  0.231  0.0  0.00  0.000  0.00
d7        0.0  0.000  0.00  0.000  0.863  0.0  0.90  0.000  0.00
d8        0.0  0.000  0.00  0.416  0.879  0.0  0.90  0.759  0.00
d9        0.0  0.149  0.00  0.000  0.681  0.8  0.75  0.721  0.00
d10       0.0  0.200  0.00  0.600  0.700  0.0  0.90  0.000  0.00

In [4]:
table4 = dec_table.export_table4()
df_table4 = show_table(table4)
df_table4

m1  m2  m3  m4  m5  m6  m7  m8  m9
Fault_ID                                    
d1         2   2   0   0   1   0   1   0   0
d2         0   1   0   1   0   0   0   2   0
d3         0   2   0   0   1   0   1   0   0
d4         0   0   0   0   2   2   2   2   0
d5         0   0   0   2   0   0   0   0   2
d6         0   2   2   0   1   0   0   0   0
d7         0   0   0   0   2   0   2   0   0
d8         0   0   0   1   2   0   2   2   0
d9         0   1   0   0   2   2   2   2   0
d10        0   1   0   2   2   0   2   0   0

In [5]:
core = find_core(dec_table)
core

{'m1', 'm2'}

In [6]:
solutions = find_min_covers_exhaustive(dec_table)
solutions

核心属性 core = {'m1', 'm2'}


[{'m1', 'm2', 'm4', 'm7', 'm8'},
 {'m1', 'm2', 'm6', 'm7', 'm8'},
 {'m1', 'm2', 'm3', 'm4', 'm8'},
 {'m1', 'm2', 'm4', 'm6', 'm7'},
 {'m1', 'm2', 'm3', 'm4', 'm6'}]

In [7]:
table_list = []
for solution in solutions:
    table_list.append(dec_table.extract_attribute_subset(solution))

for i in range(len(table_list)):
    table5 = table_list[i].export_table4()
    df_table5 = show_table(table5)
    df_table5.to_html(f'Results/table_5_{i+1}.html')

In [11]:
import numpy as np

In [14]:
np.array(list(table_list[0].fault_prior.values()))

array([0.2271, 0.0527, 0.0629, 0.0612, 0.0506, 0.1317, 0.0798, 0.1421,
       0.1202, 0.0717])

In [19]:
prob_table = show_table(table_list[0].export_table3())
prob_table

m1     m2     m4    m7     m8
Fault_ID                                
d1        0.9  0.818  0.000  0.30  0.000
d2        0.0  0.219  0.267  0.00  0.816
d3        0.0  0.713  0.000  0.35  0.000
d4        0.0  0.000  0.000  0.90  0.681
d5        0.0  0.000  0.718  0.00  0.000
d6        0.0  0.674  0.000  0.00  0.000
d7        0.0  0.000  0.000  0.90  0.000
d8        0.0  0.000  0.416  0.90  0.759
d9        0.0  0.149  0.000  0.75  0.721
d10       0.0  0.200  0.600  0.90  0.000

In [24]:
prob_table['m2']

Fault_ID
d1     0.818
d2     0.219
d3     0.713
d4     0.000
d5     0.000
d6     0.674
d7     0.000
d8     0.000
d9     0.149
d10    0.200
Name: m2, dtype: float64

In [9]:
dec_table_sim = table_list[-1]
table3 = dec_table_sim.export_table3()
temp = [d.get('m8') for d in table3.values()]
temp

[0.0, 0.816, 0.0, 0.681, 0.0, 0.0, 0.0, 0.759, 0.721, 0.0]

In [10]:
temp = 1 - np.array(temp)
temp

array([1.   , 0.184, 1.   , 0.319, 1.   , 1.   , 1.   , 0.241, 0.279,
       1.   ])

In [11]:
prior_prob = np.array([0.2271, 0.0527, 0.0629, 0.0612, 0.0506, 0.1317, 0.0798, 0.1421, 0.1202, 0.0717])
prior_prob

array([0.2271, 0.0527, 0.0629, 0.0612, 0.0506, 0.1317, 0.0798, 0.1421,
       0.1202, 0.0717])

In [12]:
results = prior_prob
results

array([0.2271, 0.0527, 0.0629, 0.0612, 0.0506, 0.1317, 0.0798, 0.1421,
       0.1202, 0.0717])

In [13]:
results = temp * results
results.round(4)

array([0.2271, 0.0097, 0.0629, 0.0195, 0.0506, 0.1317, 0.0798, 0.0342,
       0.0335, 0.0717])